MYSQL_HOST=172.24.83.45
MYSQL_PORT=3306
MYSQL_USER=isucari
MYSQL_DBNAME=isucari
MYSQL_PASS=isucari
GOOGLE_APPLICATION_CREDENTIALS=/home/isucon/.ssh/stackdriver_trace_agen_credentials.json
GOOGLE_CLOUD_PROJECT=isucon-213703
